apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
      - ./infra/k8s-dev/*.yaml
      - ./infra/local/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: holmestm/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: holmestm/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: holmestm/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: holmestm/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: holmestm/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: holmestm/client
      context: tsclient
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts*'
            dest: .
