apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
      - ./infra/gcp/*.yaml
build:
  googleCloudBuild:
    projectId: ticketing-dev-277912
  artifacts:
    - image: eu.gcr.io/ticketing-dev-277912/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/ticketing-dev-277912/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
