apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-np
spec:
  type: NodePort
  selector:
    app: orders-mongo
  ports:
    - name: orders-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
